/* ============================================================
   ETF Tracker — Top 50 ETFs by AUM
   Loads static etf-data.json (generated by update_etf_data.py
   via GitHub Actions every 30 min during market hours).
   No CORS proxy, no live API calls — instant load.
   ============================================================ */
(function () {
  'use strict';

  var DATA_URL = 'etf-data.json';
  var CACHE_KEY = 'etf_data';
  var CACHE_TTL = 10 * 60 * 1000; // 10 minutes before considering localStorage stale

  // State
  var state = {
    etfs: [],
    search: '',
    sortKey: 'marketCap',
    sortDir: -1,
    loading: false,
    updatedAt: null,
    source: ''
  };

  var els = {};

  /* ---------- Helpers ---------- */

  function $(id) { return document.getElementById(id); }

  function fmtMoney(v) {
    if (v == null || isNaN(v)) return '\u2014';
    if (v >= 1e12) return '$' + (v / 1e12).toFixed(2) + 'T';
    if (v >= 1e9)  return '$' + (v / 1e9).toFixed(1) + 'B';
    if (v >= 1e6)  return '$' + (v / 1e6).toFixed(0) + 'M';
    return '$' + v.toFixed(2);
  }

  function fmtPrice(v) {
    if (v == null || isNaN(v)) return '\u2014';
    return '$' + v.toFixed(2);
  }

  function fmtVolume(v) {
    if (v == null || isNaN(v)) return '\u2014';
    if (v >= 1e9) return (v / 1e9).toFixed(1) + 'B';
    if (v >= 1e6) return (v / 1e6).toFixed(1) + 'M';
    return v.toLocaleString();
  }

  function fmtChangePct(v) {
    if (v == null || isNaN(v)) return '\u2014';
    var s = v > 0 ? '+' : '';
    return s + v.toFixed(2) + '%';
  }

  function fmtPercent(v) {
    if (v == null || isNaN(v)) return '\u2014';
    var s = v > 0 ? '+' : '';
    return s + v.toFixed(2) + '%';
  }

  function timeAgo(ts) {
    if (!ts) return '';
    var diff = (Date.now() - ts) / 1000;
    if (diff < 5) return 'just now';
    if (diff < 60) return Math.floor(diff) + 's ago';
    if (diff < 3600) return Math.floor(diff / 60) + 'm ago';
    return Math.floor(diff / 3600) + 'h ago';
  }

  function escapeHtml(s) {
    if (s == null) return '';
    var amp = '&';
    var map = {
      '&': amp + 'amp;',
      '<': amp + 'lt;',
      '>': amp + 'gt;',
      '"': amp + 'quot;',
      "'": amp + '#39;'
    };
    return String(s).replace(/[&<>"']/g, function (c) { return map[c]; });
  }

  /* ---------- Cache ---------- */

  function getLocalCache() {
    try {
      var item = localStorage.getItem(CACHE_KEY);
      if (item) {
        var parsed = JSON.parse(item);
        if (parsed && parsed.etfs && parsed.etfs.length > 0) {
          // Only use if reasonably fresh
          if (!parsed.updatedAt || Date.now() - parsed.updatedAt < CACHE_TTL) {
            return parsed;
          }
        }
      }
    } catch (e) { /* ignore */ }
    return null;
  }

  function setLocalCache(etfs, updatedAt) {
    try {
      localStorage.setItem(CACHE_KEY, JSON.stringify({
        etfs: etfs,
        updatedAt: updatedAt || Date.now()
      }));
    } catch (e) { /* ignore */ }
  }

  /* ---------- Data loading ---------- */

  function loadData() {
    if (state.loading) return;
    state.loading = true;

    // 1) Try static JSON (same-origin, no CORS, no proxy)
    fetch(DATA_URL + '?v=' + Date.now())
      .then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(function (data) {
        if (!data || !data.etfs || !data.etfs.length) throw new Error('No data');
        state.etfs = data.etfs;
        state.updatedAt = data.updatedAt || Date.now();
        state.source = 'json';
        state.loading = false;
        setLocalCache(data.etfs, state.updatedAt);
        applyData();
      })
      .catch(function (e) {
        // 2) Fallback: localStorage cache
        var cached = getLocalCache();
        if (cached) {
          state.etfs = cached.etfs;
          state.updatedAt = cached.updatedAt;
          state.source = 'cache';
          state.loading = false;
          applyData();
        } else {
          state.loading = false;
          setStatus('Failed to load ETF data.', false);
        }
        console.error(e);
      });
  }

  function applyData() {
    // Sort by AUM desc
    state.etfs.sort(function (a, b) {
      return (b.marketCap || 0) - (a.marketCap || 0);
    });
    render();
    updateStats();
  }

  /* ---------- Stats ---------- */

  function updateStats() {
    var etfs = state.etfs;
    if (!etfs.length) return;

    var totalAum = etfs.reduce(function (sum, e) { return sum + (e.marketCap || 0); }, 0);
    var totalAumEl = $('stat-total-aum');
    if (totalAumEl) totalAumEl.textContent = fmtMoney(totalAum);

    var valid = etfs.filter(function (e) { return e.changePercent != null; });
    var topGainer = valid.length ? valid.reduce(function (a, b) { return a.changePercent > b.changePercent ? a : b; }) : null;
    var topLoser = valid.length ? valid.reduce(function (a, b) { return a.changePercent < b.changePercent ? a : b; }) : null;

    var gainerEl = $('stat-top-gainer');
    if (gainerEl) gainerEl.textContent = topGainer ? topGainer.symbol + ' ' + fmtPercent(topGainer.changePercent) : '\u2014';

    var loserEl = $('stat-top-loser');
    if (loserEl) loserEl.textContent = topLoser ? topLoser.symbol + ' ' + fmtPercent(topLoser.changePercent) : '\u2014';

    var avgChange = valid.length ? valid.reduce(function (sum, e) { return sum + e.changePercent; }, 0) / valid.length : null;
    var avgEl = $('stat-avg-change');
    if (avgEl) avgEl.textContent = avgChange != null ? fmtPercent(avgChange) : '\u2014';
  }

  /* ---------- Rendering ---------- */

  function getFiltered() {
    var q = state.search.trim().toLowerCase();
    var all = state.etfs.slice();

    if (q) {
      all = all.filter(function (item) {
        return (item.symbol || '').toLowerCase().indexOf(q) !== -1 ||
               (item.name || '').toLowerCase().indexOf(q) !== -1;
      });
    }

    var key = state.sortKey;
    var dir = state.sortDir;
    all = all.slice().sort(function (a, b) {
      var va = key === 'rank' ? a.marketCap : a[key];
      var vb = key === 'rank' ? b.marketCap : b[key];
      if (va == null) return -1 * dir;
      if (vb == null) return 1 * dir;
      if (typeof va === 'string') {
        return va.localeCompare(vb) * dir;
      }
      return (va - vb) * dir;
    });

    return all;
  }

  function render() {
    var all = getFiltered();
    var body = els.body;
    body.innerHTML = '';

    var rankCounter = 0;
    all.forEach(function (item) {
      rankCounter++;
      item._displayRank = rankCounter;
      var tr = document.createElement('tr');
      tr.setAttribute('data-symbol', item.symbol);
      tr.setAttribute('data-type', item.type);

      var changeCls = item.changePercent > 0 ? 'pos' : item.changePercent < 0 ? 'neg' : 'flat';

      tr.innerHTML =
        '<td class="rank">' + item._displayRank + '</td>' +
        '<td class="symbol-col">' +
          '<span class="ticker">' + escapeHtml(item.symbol) + '</span>' +
        '</td>' +
        '<td class="name-col">' + escapeHtml(item.name) + '</td>' +
        '<td class="num price">' + fmtPrice(item.price) + '</td>' +
        '<td class="num ' + changeCls + '">' + fmtChangePct(item.changePercent) + '</td>' +
        '<td class="num muted">' + fmtVolume(item.volume) + '</td>' +
        '<td class="num marketcap">' + fmtMoney(item.marketCap) + '</td>' +
        '<td class="num muted">' + fmtPrice(item.high) + '</td>' +
        '<td class="num muted">' + fmtPrice(item.low) + '</td>';

      body.appendChild(tr);
    });

    els.count.textContent = all.length + ' ETFs';
    els.updated.textContent = state.updatedAt ? 'Updated ' + timeAgo(state.updatedAt) + ' \u00b7 Yahoo Finance' : '';

    if (all.length > 0) {
      els.status.hidden = true;
      els.tableWrap.hidden = false;
    } else {
      els.status.hidden = false;
      els.tableWrap.hidden = true;
      setStatus(state.loading ? 'Loading\u2026' : (state.search ? 'No matches found' : 'No data available'), !state.loading);
    }

    document.querySelectorAll('.etf-table th[data-sort]').forEach(function (th) {
      th.classList.toggle('sorted', th.getAttribute('data-sort') === state.sortKey);
      th.classList.toggle('asc', th.getAttribute('data-sort') === state.sortKey && state.sortDir === 1);
      th.classList.toggle('desc', th.getAttribute('data-sort') === state.sortKey && state.sortDir === -1);
    });
  }

  function setStatus(msg, isInfo) {
    if (els.status) {
      els.status.innerHTML = '';
      els.status.hidden = false;
      var icon;
      if (isInfo) {
        icon = '<div class="spinner"></div>';
      } else {
        icon = '<span class="status-icon">\u26A0</span>';
      }
      els.status.innerHTML = icon + '<p>' + escapeHtml(msg) + '</p>';
      if (!isInfo) {
        els.status.classList.add('error');
      } else {
        els.status.classList.remove('error');
      }
    }
  }

  /* ---------- Events ---------- */

  function initEvents() {
    var searchTimer;
    els.search.addEventListener('input', function () {
      clearTimeout(searchTimer);
      searchTimer = setTimeout(function () {
        state.search = els.search.value;
        render();
      }, 200);
    });

    els.refresh.addEventListener('click', function () {
      loadData();
    });

    document.querySelectorAll('.etf-table th[data-sort]').forEach(function (th) {
      th.addEventListener('click', function () {
        var key = th.getAttribute('data-sort');
        if (state.sortKey === key) {
          state.sortDir *= -1;
        } else {
          state.sortKey = key;
          state.sortDir = 1;
        }
        render();
      });
    });

    var navToggle = $('nav-toggle');
    var nav = $('nav');
    if (navToggle && nav && !navToggle.dataset.etfBound) {
      navToggle.dataset.etfBound = '1';
      navToggle.addEventListener('click', function () {
        nav.classList.toggle('open');
      });
    }
  }

  /* ---------- Init ---------- */

  function init() {
    els.body = $('stocks-body');
    els.status = $('stocks-status');
    els.tableWrap = $('stocks-table-wrap');
    els.count = $('stocks-count');
    els.updated = $('stocks-updated');
    els.search = $('search-input');
    els.refresh = $('refresh-btn');

    if (!els.body) return;

    var yearEl = $('year');
    if (yearEl) yearEl.textContent = new Date().getFullYear();

    initEvents();

    // 1) Render cached data immediately (no flash, no spinner)
    var cached = getLocalCache();
    if (cached) {
      state.etfs = cached.etfs;
      state.updatedAt = cached.updatedAt;
      render();
      updateStats();
      if (els.status) els.status.hidden = true;
      if (els.tableWrap) els.tableWrap.hidden = false;
    }

    // 2) Load static JSON (same-origin, instant)
    loadData();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();